// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKljyV8RwGqdayOCn8MNPnUegtlEPsYw',
    appId: '1:532978627700:web:17541562e1816ce4574d21',
    messagingSenderId: '532978627700',
    projectId: 'twitch-clone-f711b',
    authDomain: 'twitch-clone-f711b.firebaseapp.com',
    storageBucket: 'twitch-clone-f711b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk098ymnhZiTkFQOe0t5LkU9AjxBl-Z40',
    appId: '1:532978627700:android:880afe29bf3cca0e574d21',
    messagingSenderId: '532978627700',
    projectId: 'twitch-clone-f711b',
    storageBucket: 'twitch-clone-f711b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrJgeLX3dyHhwrZe1hCy7sTU0ZwfSdPc',
    appId: '1:532978627700:ios:ffb293ff2cc1887c574d21',
    messagingSenderId: '532978627700',
    projectId: 'twitch-clone-f711b',
    storageBucket: 'twitch-clone-f711b.appspot.com',
    iosBundleId: 'com.ly.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrJgeLX3dyHhwrZe1hCy7sTU0ZwfSdPc',
    appId: '1:532978627700:ios:ffb293ff2cc1887c574d21',
    messagingSenderId: '532978627700',
    projectId: 'twitch-clone-f711b',
    storageBucket: 'twitch-clone-f711b.appspot.com',
    iosBundleId: 'com.ly.twitchClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKljyV8RwGqdayOCn8MNPnUegtlEPsYw',
    appId: '1:532978627700:web:c7e7d8bebca5205b574d21',
    messagingSenderId: '532978627700',
    projectId: 'twitch-clone-f711b',
    authDomain: 'twitch-clone-f711b.firebaseapp.com',
    storageBucket: 'twitch-clone-f711b.appspot.com',
  );
}
